### PR TITLE
Upgrade to node 6 LTS

### PR DESCRIPTION
**Pull request by m7moud**

### CODE REVIEW

**Comment by marek-obuchowicz** [comment]
How does it relate to https://github.com/spryker/devvm/issues/24 ?
Can you please clarify expected node versions together? @m7moud @abelspry

**Review by marek-obuchowicz — DISMISSED** [review]

**Comment by thomaskuehnel** [comment]
Could you please clarify these kinds of updates with @abelspry? It might have impact on bulding assets.

**Comment by thomaskuehnel** [comment]
Just saw that @marek-obuchowicz already mentioned this :-D. Sorry for the duplication

**Comment by ghost** [comment]
Version 4 is LTS too and provides more compatibility (in terms of modules) compared to 6. 
I'd like to move to 6 though, but we need to test our environment first. I'm executing tests in these days, I'll keep you informed.
@marek-obuchowicz @m7moud @ThomasKuehnel

**Review by ghost — CHANGES_REQUESTED** [review]
I have to block the PR for the moment, waiting for some test results. I'm on them.

**Comment by marek-obuchowicz** [comment]
Perfect, let us know. We might also have some running customer projects already started with the old VM, they might get updated to 6 with this PR, so please test throughly... :)

**Comment by m7moud** [comment]
Updated already!

**Pull request closed without merging**
